### ISSUE TITLE
Looks good - Some Changes

### ISSUE THREAD

**Issue by Tritium-VLK** [Soptq/gnosis-safe-delegate-dapp#1]
1: We need to use this for mainnet.  Please accept the web3 url and the safe url as environment variables so these can be set and provide example env files for both mainnet and testnet.

2: chainid also needs to be a variable (not hardcoded) and set based on the selected network (another env var)

After making these changes to operate on mainnet I am still unable to add a delegate.  The java console throws a 400 bad request after I sign with metamask when trying to submit the add delegate command.

Please feel free to get in touch with us on our Dev Discord here:  https://discord.gg/zEDdtWeC

You can find me there as Tritium-VLK.  You look close, we'd love to get this up and running.  When gas is cheap we suggest you fire up your own mainnet safe to test with.  It should only cost 20-30 bucks at under 30 gwei.

**Comment by Soptq** [comment]
Fixed.
